name: sard
description: "A beautiful application for ordering chocolate."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  shared_preferences: ^2.3.2
  flutter_dotenv: ^6.0.0
  flutter:
    sdk: flutter
  transparent_image: ^2.0.1
  flutter_secure_storage: ^10.0.0
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  uuid: ^4.5.2
  path: ^1.9.1
  permission_handler: ^12.0.1
  table_calendar:
    git:
      url: https://github.com/yahyazawadi/table_calendar.git
      ref: border-days
  go_router: ^14.3.0
  flutter_localizations:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  firebase_auth: ^6.4.0
  google_sign_in: ^6.1.0
  app_links: ^6.3.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  mask_text_input_formatter: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/iconSARD_final.png"
  adaptive_icon_background: "#5ec5c3"
  adaptive_icon_foreground: "assets/images/iconSARD_final.png"



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/data/

  fonts:
    - family: DG Sahabah
      fonts:
        - asset: assets/fonts/DG-Sahabah-Light.ttf
          weight: 300
        - asset: assets/fonts/DG-Sahabah-Reg.ttf
          weight: 400
        - asset: assets/fonts/DG-Sahabah-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#5ec5c3"
  image: assets/images/WhiteLogo.png
  android: true
  ios: true
  android_12:
    color: "#5ec5c3"
    image: assets/images/WhiteLogo.png


