// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzt3NQ6vAHztbgKSDDo83nMVfHl5ncZpk',
    appId: '1:313420731986:web:7eb9481b29a25b2fdd718b', // Placeholder web for new project
    messagingSenderId: '313420731986',
    projectId: 'flutter-ai-playground-96a06',
    authDomain: 'flutter-ai-playground-96a06.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-96a06.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzt3NQ6vAHztbgKSDDo83nMVfHl5ncZpk',
    appId: '1:313420731986:android:e8d7458bfdb07478dd718b',
    messagingSenderId: '313420731986',
    projectId: 'flutter-ai-playground-96a06',
    storageBucket: 'flutter-ai-playground-96a06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzt3NQ6vAHztbgKSDDo83nMVfHl5ncZpk',
    appId: '1:313420731986:ios:fc174b3d98a25b2fdd718b', // Placeholder iOS for new project
    messagingSenderId: '313420731986',
    projectId: 'flutter-ai-playground-96a06',
    storageBucket: 'flutter-ai-playground-96a06.firebasestorage.app',
    iosBundleId: 'com.example.sarad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzt3NQ6vAHztbgKSDDo83nMVfHl5ncZpk',
    appId: '1:313420731986:ios:fc174b3d98a25b2fdd718b',
    messagingSenderId: '313420731986',
    projectId: 'flutter-ai-playground-96a06',
    storageBucket: 'flutter-ai-playground-96a06.firebasestorage.app',
    iosBundleId: 'com.example.sarad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzt3NQ6vAHztbgKSDDo83nMVfHl5ncZpk',
    appId: '1:313420731986:web:7eb9481b29a25b2fdd718b',
    messagingSenderId: '313420731986',
    projectId: 'flutter-ai-playground-96a06',
    authDomain: 'flutter-ai-playground-96a06.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-96a06.firebasestorage.app',
  );
}
